name: dartlr
version: 0.0.3
description: >
  Dart code generation for the parser generator antlr.
  Generates Dart code compatible with the M1 release.
  
authors:
- Tiago Mazzutti <tiagomzt@gmail.com>
- Karl Guggisberg <karl.guggisberg@guggis.ch>

homepage: https://github.com/tiagomazzutti/dartlr.git
  
dependencies:
  unittest: any
  logging: any
  meta: any
