name: dartlr
version: 0.3.0
description: >
  Dart code generation for the parser generator antlr.
  
authors:
- Tiago Mazzutti <tiagomzt@gmail.com>
- Karl Guggisberg <karl.guggisberg@guggis.ch>

homepage: https://github.com/tiagomazzutti/dartlr.git
  
dependencies:
  unittest: any
  logging: any
  meta: any
